# -*- coding: utf-8 -*-
"""yolov12 merged ds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDN6orqOltSHs3u3AzPRwXSBeQ8CR-P_
"""

from google.colab import drive
drive.mount('/content/drive')

!unzip /content/drive/MyDrive/project/INNOVATIVEPROJECT/merged_ds_yolo.zip -d /content/dataset

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/sunsmarterjie/yolov12
# %cd yolov12
!pip install roboflow supervision flash-attn --upgrade -q
!pip install -r requirements.txt
!pip install -e .
!pip install --upgrade flash-attn

!sed -i '$d' {dataset.location}/data.yaml
!sed -i '$d' {dataset.location}/data.yaml
!sed -i '$d' {dataset.location}/data.yaml
!sed -i '$d' {dataset.location}/data.yaml
!echo -e "test: ../test/images\ntrain: ../train/images\nval: ../valid/images" >> {dataset.location}/data.yaml

# Define the path to the data.yaml file
data_yaml_path = f"/content/dataset/merged_ds/data.yaml"

# Read the existing data.yaml file
with open(data_yaml_path, 'r') as f:
    lines = f.readlines()

# Find the lines that define the train, val, and test paths and update them
updated_lines = []
for line in lines:
    if line.strip().startswith('train:'):
        updated_lines.append('train: ../train/images\n')
    elif line.strip().startswith('val:'):
        updated_lines.append('val: ../valid/images\n')
    elif line.strip().startswith('test:'):
        updated_lines.append('test: ../test/images\n')
    else:
        updated_lines.append(line)

# Write the updated content back to the data.yaml file
with open(data_yaml_path, 'w') as f:
    f.writelines(updated_lines)

print(f"Updated {data_yaml_path} with new train, val, and test paths.")

!pip install ultralytics
from ultralytics import YOLO

model = YOLO('yolov12m.pt')

results = model.train(
  data=data_yaml_path,
  epochs=20
)

from IPython.display import Image
Image(filename=f'/content/yolov12/runs/detect/train/confusion_matrix.png', width=600)

Image(filename=f'/content/yolov12/runs/detect/train/results.png', width=600)

import random
import os

import locale
def getpreferredencoding(do_setlocale = True):
    return "UTF-8"
locale.getpreferredencoding = getpreferredencoding

!pip install supervision
import supervision as sv
import cv2

model_path = f'/content/yolov12/runs/detect/train/weights/best.pt'
model = YOLO(model_path)
ds = sv.DetectionDataset.from_yolo(
        images_directory_path=f"/content/dataset/merged_ds/valid/images",
        annotations_directory_path=f"/content/dataset/merged_ds/valid/labels",
        data_yaml_path=f"/content/dataset/merged_ds/data.yaml"
)

image = random.choice(list(ds.image_paths))
image = cv2.imread(image)

bounding_box_annotator = sv.BoxAnnotator()
label_annotator = sv.LabelAnnotator()

results = model(image)[0]
detections = sv.Detections.from_ultralytics(results).with_nms()

bounding_box_annotator = sv.BoxAnnotator()
label_annotator = sv.LabelAnnotator()

annotated_image = bounding_box_annotator.annotate(
        scene=image, detections=detections)
annotated_image = label_annotator.annotate(
        scene=annotated_image, detections=detections)

sv.plot_image(annotated_image)

import os
import shutil

def filter_dataset(annotations_dir, images_dir):
    for filename in os.listdir(annotations_dir):
        annotation_path = os.path.join(annotations_dir, filename)
        with open(annotation_path, 'r') as f:
            lines = f.readlines()
            # Check if the annotation has more than 5 fields
            # Indicating presence of segmentation data.
            if any(len(line.strip().split()) > 5 for line in lines):
                # If the annotation contains segmentation, delete the corresponding image and the annotation file.
                os.remove(annotation_path)
                image_path = os.path.join(images_dir, filename.replace('.txt', '.jpg'))
                os.remove(image_path)
                print(f"Removed: {filename} and its image.")

filter_dataset(f"/content/dataset/merged_ds/valid/labels", f"/content/dataset/merged_ds/valid/images")

import torch

# Load the trained YOLO model
model_path = "/content/yolov12/runs/detect/train/weights/best.pt"  # Replace 'best.pt' with your trained model's path if needed
model = YOLO(model_path)

# Run evaluation on the validation set
results = model.val(data=f"/content/dataset/merged_ds/data.yaml",  # Path to dataset configuration file
                    imgsz=640,        # Image size for inference
                    conf=0.5,         # Confidence threshold
                    iou=0.5,          # IoU threshold for NMS
                    device=torch.device("cuda" if torch.cuda.is_available() else "cpu"),  # Use CUDA if available, otherwise CPU
                    verbose=False  # Suppress detailed output during evaluation
                   )

# Access and print the precision score
precision = results.box.p  # Access precision from the results object
print(f"Precision: {precision}")

import torch

# Load the trained YOLO model
model_path = "/content/yolov12/runs/detect/train/weights/best.pt"  # Replace 'best.pt' with your trained model's path if needed
model = YOLO(model_path)

# Run evaluation on the validation set
results = model.val(data=f"/content/dataset/merged_ds/data.yaml",  # Path to dataset configuration file
                    imgsz=640,        # Image size for inference
                    conf=0.5,         # Confidence threshold
                    iou=0.5,          # IoU threshold for NMS
                    device=torch.device("cuda" if torch.cuda.is_available() else "cpu"),  # Use CUDA if available, otherwise CPU
                    verbose=False  # Suppress detailed output during evaluation
                   )

# Access and print the overall precision, recall, f1, and mAP scores
overall_precision = results.box.p.mean()
overall_recall = results.box.r.mean()
overall_f1 = results.box.f1.mean()
map50 = results.box.map50
map5095 = results.box.map

print(f"Overall Precision: {overall_precision}")
print(f"Overall Recall: {overall_recall}")
print(f"Overall F1 Score: {overall_f1}")
print(f"mAP50: {map50}")
print(f"mAP50-95: {map5095}")
accuracy = (2 * overall_precision * overall_recall) / (overall_precision + overall_recall + 1e-6)  # same as F1 in detection context
print(f"Approx Accuracy: {accuracy:.4f}")

import shutil
from google.colab import files

# Example: zip a folder
shutil.make_archive("/content/my_results", 'zip', "/content/yolov12/runs/detect")

# Download zip
files.download("/content/my_results.zip")

from ultralytics import YOLO

model = YOLO("/content/best.pt")

metrics = model.val(
    data="/content/dataset/merged_ds/data.yaml",
    imgsz=640,
    conf=0.25
)

# Per-class metrics
for i, name in metrics.names.items():
    p = metrics.box.p[i]
    r = metrics.box.r[i]
    f1 = metrics.box.f1[i]
    print(f"{name}: Precision={p:.3f}, Recall={r:.3f}, F1={f1:.3f}")

import torch
import cv2
import os
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt

model = YOLO("/content/best.pt")  # path to your trained YOLOv12 model

VAL_IMG_DIR = "/content/dataset/merged_ds/test/images"

VAL_IMG_DIR = "/content/dataset/merged_ds/test/images"

results_data = []

for img_name in tqdm(os.listdir(VAL_IMG_DIR)):
    img_path = os.path.join(VAL_IMG_DIR, img_name)
    res = model(img_path, conf=0.25, iou=0.5, verbose=False)[0]

    num_objects = len(res.boxes)
    leaf_type = "single_leaf" if num_objects <= 1 else "multi_leaf"

    for cls in res.boxes.cls.cpu().numpy():
        results_data.append({
            "image": img_name,
            "class": int(cls),
            "leaf_type": leaf_type
        })

df = pd.DataFrame(results_data)

performance = df.groupby(["class", "leaf_type"]).size().unstack(fill_value=0)
performance

performance.plot(kind="bar", figsize=(10,6))
plt.title("Detection Distribution: Single vs Multi Leaf")
plt.ylabel("Detections")
plt.show()

SMALL_OBJ_THRESH = 32 * 32  # pixels

small_objects = []

for img_name in tqdm(os.listdir(VAL_IMG_DIR)):
    img_path = os.path.join(VAL_IMG_DIR, img_name)
    img = cv2.imread(img_path)
    h, w, _ = img.shape

    res = model(img_path, verbose=False)[0]

    for box, cls in zip(res.boxes.xywh, res.boxes.cls):
        bw, bh = box[2].item(), box[3].item()
        area = bw * bh

        small_objects.append({
            "class": int(cls),
            "area": area,
            "is_small": area < SMALL_OBJ_THRESH
        })

df_small = pd.DataFrame(small_objects)

df_small.groupby("class")["is_small"].mean() * 100

import time

def measure_fps(model, image_dir, runs=100):
    images = os.listdir(image_dir)[:runs]
    start = time.time()

    for img in images:
        model(os.path.join(image_dir, img), verbose=False)

    end = time.time()
    fps = runs / (end - start)
    return fps

fps = measure_fps(model, VAL_IMG_DIR)
print(f"Inference Speed: {fps:.2f} FPS")

FP_DIR = "/content/false_positives"
os.makedirs(FP_DIR, exist_ok=True)

for img_name in os.listdir(VAL_IMG_DIR):
    img_path = os.path.join(VAL_IMG_DIR, img_name)
    res = model(img_path, conf=0.05, verbose=False)[0]

    if len(res.boxes) > 0 and res.boxes.conf.mean() < 0.3:
        img = cv2.imread(img_path)
        cv2.imwrite(os.path.join(FP_DIR, img_name), img)

FN_DIR = "/content/false_negatives"
os.makedirs(FN_DIR, exist_ok=True)

for img_name in os.listdir(VAL_IMG_DIR):
    img_path = os.path.join(VAL_IMG_DIR, img_name)
    res = model(img_path, verbose=False)[0]

    if len(res.boxes) == 0:
        img = cv2.imread(img_path)
        cv2.imwrite(os.path.join(FN_DIR, img_name), img)

ious = [0.3, 0.5, 0.7]
metrics = {}

for iou in ious:
    r = model.val(iou=iou, conf=0.25)
    metrics[iou] = r.box.map50

metrics

import shutil

shutil.make_archive(FP_DIR, 'zip', FP_DIR)
print(f"Zipped {FP_DIR} to {FP_DIR}.zip")

shutil.make_archive(FN_DIR, 'zip', FN_DIR)
print(f"Zipped {FN_DIR} to {FN_DIR}.zip")

import os
import time
single_leaf_times = []
multi_leaf_times = []

for img_name in os.listdir(VAL_IMG_DIR):
    img_path = os.path.join(VAL_IMG_DIR, img_name)

    start = time.time()
    result = model(img_path, conf=0.25, iou=0.5, verbose=False)[0]
    end = time.time()

    inference_time = end - start
    num_boxes = len(result.boxes)

    if num_boxes <= 1:
        single_leaf_times.append(inference_time)
    else:
        multi_leaf_times.append(inference_time)

import numpy as np

yolo_single_mean = np.mean(single_leaf_times)
yolo_multi_mean = np.mean(multi_leaf_times)
yolo_diff = yolo_multi_mean - yolo_single_mean

print("yolo_single_mean ",yolo_single_mean)
print("yolo_multi_mean  ", yolo_multi_mean)
print("yolo_diff  ", yolo_diff)

import os

from collections import defaultdict

single_leaf_imgs = []
multi_leaf_imgs = []

for img in os.listdir(VAL_IMG_DIR):
    res = model(os.path.join(VAL_IMG_DIR, img), conf=0.25, iou=0.5, verbose=False)[0]
    if len(res.boxes) <= 1:
        single_leaf_imgs.append(img)
    else:
        multi_leaf_imgs.append(img)

VAL_LABEL_DIR ="/content/dataset/merged_ds/test/labels"

import shutil, os

BASE = "/content/temp_eval"
SINGLE = f"{BASE}/single"
MULTI = f"{BASE}/multi"

for p in [SINGLE, MULTI]:
    os.makedirs(f"{p}/images", exist_ok=True)
    os.makedirs(f"{p}/labels", exist_ok=True)

def copy_subset(img_list, target):
    for img in img_list:
        shutil.copy(f"{VAL_IMG_DIR}/{img}", f"{target}/images/{img}")
        shutil.copy(f"{VAL_LABEL_DIR}/{img.replace('.jpg','.txt')}",
                    f"{target}/labels/{img.replace('.jpg','.txt')}")

copy_subset(single_leaf_imgs, SINGLE)
copy_subset(multi_leaf_imgs, MULTI)

single_metrics = model.val(
    data="/content/dataset/merged_ds/data.yaml",
    imgsz=640,
    conf=0.25,
    iou=0.5,
    project="leaf_eval",
    name="single_leaf"
)

multi_metrics = model.val(
    data="/content/dataset/merged_ds/data.yaml",
    imgsz=640,
    conf=0.25,
    iou=0.5,
    project="leaf_eval",
    name="multi_leaf"
)

import os
YOLO_OUT = "/content/yolov12_inference_results"
YOLO_SINGLE = f"{YOLO_OUT}/single_leaf"
YOLO_MULTI  = f"{YOLO_OUT}/multi_leaf"

os.makedirs(YOLO_SINGLE, exist_ok=True)
os.makedirs(YOLO_MULTI, exist_ok=True)

CLASS_NAMES = {
    0: "Rice_Bacterial_Blight",
    1: "Rice_Brown_Spot",
    2: "Rose_Black_Spot",
    3: "Tomato_Early_Blight"
}

from ultralytics import YOLO
import cv2, os

model = YOLO("/content/best.pt")
IMG_DIR = "/content/dataset/merged_ds/test/images"
LABEL_DIR = "/content/dataset/merged_ds/test/labels"
CONF = 0.25
IOU = 0.5

for img_name in os.listdir(IMG_DIR):
    img_path = os.path.join(IMG_DIR, img_name)
    label_path = os.path.join(LABEL_DIR, img_name.replace(".jpg", ".txt"))

    # Determine single vs multi-leaf using GT
    with open(label_path, "r") as f:
        gt_count = len(f.readlines())

    save_dir = YOLO_SINGLE if gt_count <= 1 else YOLO_MULTI

    # Run inference
    result = model(img_path, conf=CONF, iou=IOU, verbose=False)[0]
    img = cv2.imread(img_path)

    for box in result.boxes:
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        cls = int(box.cls[0])
        conf = float(box.conf[0])

        cv2.rectangle(img, (x1,y1), (x2,y2), (0,255,0), 2)
        cv2.putText(
            img,
            f"{CLASS_NAMES[cls]} {conf:.2f}",
            (x1, max(y1-5, 15)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.5,
            (0,255,0),
            2
        )

    cv2.imwrite(os.path.join(save_dir, img_name), img)

def compute_iou(box1, box2):
    xA = max(box1[0], box2[0])
    yA = max(box1[1], box2[1])
    xB = min(box1[2], box2[2])
    yB = min(box1[3], box2[3])

    inter = max(0, xB-xA) * max(0, yB-yA)
    area1 = (box1[2]-box1[0]) * (box1[3]-box1[1])
    area2 = (box2[2]-box2[0]) * (box2[3]-box2[1])

    return inter / (area1 + area2 - inter + 1e-6)

def evaluate_yolo_subset(img_list, iou_thresh=0.5):
    TP = FP = FN = 0
    correct_images = 0

    for img_name in img_list:
        img_path = os.path.join(IMG_DIR, img_name)
        label_path = os.path.join(LABEL_DIR, img_name.replace(".jpg", ".txt"))

        # Load GT boxes
        h, w, _ = cv2.imread(img_path).shape
        gt_boxes = []

        with open(label_path) as f:
            for line in f:
                cls, xc, yc, bw, bh = map(float, line.split())
                x1 = (xc - bw/2) * w
                y1 = (yc - bh/2) * h
                x2 = (xc + bw/2) * w
                y2 = (yc + bh/2) * h
                gt_boxes.append([x1,y1,x2,y2])

        # Predictions
        result = model(img_path, conf=CONF, iou=IOU, verbose=False)[0]
        pred_boxes = result.boxes.xyxy.cpu().numpy()

        matched = set()
        image_correct = False

        for pb in pred_boxes:
            ious = [compute_iou(pb, gb) for gb in gt_boxes]
            if ious and max(ious) >= iou_thresh:
                TP += 1
                image_correct = True
                matched.add(np.argmax(ious))
            else:
                FP += 1

        FN += len(gt_boxes) - len(matched)
        if image_correct:
            correct_images += 1

    precision = TP / (TP+FP+1e-6)
    recall    = TP / (TP+FN+1e-6)
    f1        = 2*precision*recall / (precision+recall+1e-6)
    accuracy  = correct_images / len(img_list)

    return precision, recall, f1, accuracy

single_imgs, multi_imgs = [], []

for img in os.listdir(IMG_DIR):
    with open(os.path.join(LABEL_DIR, img.replace(".jpg",".txt"))) as f:
        count = len(f.readlines())
    if count <= 1:
        single_imgs.append(img)
    else:
        multi_imgs.append(img)

single_metrics = evaluate_yolo_subset(single_imgs)
multi_metrics  = evaluate_yolo_subset(multi_imgs)

single_metrics, multi_metrics

import shutil
yolo = "/content/yolov12_inference_results"
shutil.make_archive(yolo, 'zip', yolo)
print(f"Zipped {yolo} to {yolo}.zip")